version: '3.8'

services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft
    environment:
      - EULA=true
      - ONLINE_MODE=false
      - MEMORY=8G
      - VERSION=1.20.1          # Minecraft version
      - TYPE=FORGE              # Use Forge for mods
      - FORGE_INSTALLER=forge-1.20.1-47.2.17-installer.jar
    ports:
      - "25564:25565"            # Port mapping for Minecraft server (host:container)
    volumes:
      - ~/minecraft:/data        # Volume for server data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped      # Restart the container in case of errors
